// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthCheckHealthGetResponse, GetDataApiKeysGetResponse, CreateKeyApiKeysPostResponse, PredictApiKnrPredictGetData, PredictApiKnrPredictGetResponse, ListApiKnrListGetResponse, NewKnrApiKnrNewPostResponse } from './types.gen';

export class DefaultService {
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheckHealthGet(): CancelablePromise<HealthCheckHealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
    
    /**
     * Get Data
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getDataApiKeysGet(): CancelablePromise<GetDataApiKeysGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/keys'
        });
    }
    
    /**
     * Create Key
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createKeyApiKeysPost(): CancelablePromise<CreateKeyApiKeysPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/keys'
        });
    }
    
    /**
     * Predict
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static predictApiKnrPredictGet(data: PredictApiKnrPredictGetData): CancelablePromise<PredictApiKnrPredictGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/knr/predict',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listApiKnrListGet(): CancelablePromise<ListApiKnrListGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/knr/list'
        });
    }
    
    /**
     * New Knr
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static newKnrApiKnrNewPost(): CancelablePromise<NewKnrApiKnrNewPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/knr/new'
        });
    }
    
}