// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type RequestPredict = {
    KNR: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthCheckHealthGetResponse = ({
    [key: string]: unknown;
});

export type GetDataApiKeysGetResponse = ({
    [key: string]: unknown;
});

export type CreateKeyApiKeysPostResponse = ({
    [key: string]: unknown;
});

export type PredictApiKnrPredictGetData = {
    requestBody: RequestPredict;
};

export type PredictApiKnrPredictGetResponse = (unknown);

export type ListApiKnrListGetResponse = (unknown);

export type NewKnrApiKnrNewPostResponse = (unknown);